labels:
  - name: "help wanted"
    description: "Extra attention is needed"
    color: "008672"
  - name: "good first issue"
    description: "Good for newcomers"
    color: "7057FF"
  - name: "priority/unknown"
    description: "Unknown priority issue/feature"
    color: "FE2689"
  - name: "priority/low"
    description: "Low priority issue/feature"
    color: "9EDF4C"
  - name: "priority/medium"
    description: "Medium priority issue/feature"
    color: "D9FD89"
  - name: "priority/high"
    description: "High priority issue/feature"
    color: "E336BF"
  - name: "stage/new"
    description: "Newly created issue"
    color: "DB44B5"
  - name: "stage/thinking"
    description: "On thinking process, what should be next move"
    color: "E1C34E"
  - name: "stage/question"
    description: "Further information is requested"
    color: "1A68DF"
  - name: "stage/accepted"
    description: "Confirmed, and intend to work on. No timeline committment though."
    color: "2E5242"
  - name: "stage/ready"
    description: "Ready to be merge"
    color: "56C5AE"
  - name: "type/duplication"
    description: "This issue or pull request already exists"
    color: "B82E0F"
  - name: "type/bug"
    description: "Something isn't working"
    color: "D129DA"
  - name: "type/documentation"
    description: "Improvements or additions to documentation"
    color: "0075CA"
  - name: "type/invalid"
    description: "This doesn't seem right to repository"
    color: "E4E669"
  - name: "type/wontfix"
    description: "This will not be worked on"
    color: "FBBF70"
  - name: "type/dependencies"
    description: "Improvement or additions to dependencies list"
    color: "F6A0D7"
