labels:
  - name: "autorelease: pending"
    description: "Initial state of the Release PR before it is merged"
    color: "EDEDED"
  - name: "autorelease: tagged"
    description: "Release PR has been merged and the release has been tagged in GitHub"
    color: "EDEDED"
  - name: "autorelease: snapshot"
    description: "Special state for snapshot version bumps"
    color: "EDEDED"
  - name: "autorelease: published"
    description: "Release has been published based on the Release PR"
    color: "EDEDED"
