name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: src/go.mod
          cache-dependency-path: src/go.sum
      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          workdir: src
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
